# Generated by Django 2.1 on 2018-08-16 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='headshot_img',
            field=models.ImageField(blank=True, null=True, upload_to='clients_hs_image'),
        ),
    ]
